spring.application.name=ejercicios-fisica

# Oracle Autonomous Database
spring.datasource.url=jdbc:oracle:thin:@${DB_TNS_ALIAS}?TNS_ADMIN=${WALLET_PATH}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver


# spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true